# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

root = Path(SPECPATH).parent
launcher = Path(SPECPATH)

a = Analysis(
    [str(launcher / "dmed_launcher.py")],
    pathex=[str(launcher), str(root / "backend")],
    binaries=[],
    datas=[
        (str(launcher / "postgres_manager.py"), "launcher"),
    ],
    hiddenimports=[
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "fastapi",
        "starlette",
        "pydantic",
        "pydantic_settings",
        "sqlalchemy",
        "psycopg2",
        "bcrypt",
        "jose",
        "email_validator",
        "redis",
        "prometheus_client",
        "sklearn",
        "joblib",
        "numpy",
        "pandas",
        "app",
        "app.main",
        "app.core",
        "app.core.config",
        "app.core.database",
        "app.core.init_db",
        "app.core.security",
        "app.core.websocket",
        "app.core.metrics",
        "app.api.v1.auth",
        "app.api.v1.patients",
        "app.api.v1.admin",
        "app.api.v1.appointments",
        "app.models",
        "app.models.user",
        "app.models.patient",
        "app.models.bed",
        "app.models.doctor",
        "app.models.hospital",
        "app.models.appointment",
        "app.schemas",
        "app.schemas.user",
        "app.schemas.patient",
        "app.schemas.bed",
        "app.schemas.appointment",
        "app.services.triage",
        "app.services.bed_allocator",
        "app.services.notification",
        "app.services.emr_integration",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="DMed",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="DMed",
)
